development:
    adapter: postgresql
    encoding: unicode
    database: periodical_development
    pool: 5
    username: postgres
    password:
    host: localhost

test:
    adapter: postgresql
    encoding: unicode
    database: periodical_test
    pool: 5
    username: postgres
    password:
    host: localhost

production:
    adapter: postgresql
    encoding: unicode
    database: periodical_production
    pool: 5
    username: postgres
    password:
    host: localhost
